#!/bin/sh

# Check python/python3 existence
if command -v python3 &>/dev/null; then
    PYTHON_EXEC=$(command -v python3)
elif command -v python &>/dev/null; then
    PYTHON_EXEC=$(command -v python)
else
    echo "Python not found"
    exit 1
fi

$PYTHON_EXEC src/godork.py "$@"